import type { BenchModel } from "./types";

/** Available vision models for benchmarking — sorted by tier then input price */
export const BENCH_MODELS: BenchModel[] = [
  // ── Ultra-budget (< $0.10/1M input) ──────────────────────────────────────
  {
    id: "google/gemma-3-27b-it",
    label: "Gemma 3 27B",
    provider: "Google",
    tier: "light",
    pricingPer1M: { input: 0.04, output: 0.15 },
    contextWindow: 128_000,
  },
  {
    id: "amazon/nova-lite-v1",
    label: "Nova Lite",
    provider: "Amazon",
    tier: "light",
    pricingPer1M: { input: 0.06, output: 0.24 },
    contextWindow: 300_000,
  },
  {
    id: "meta-llama/llama-4-scout",
    label: "Llama 4 Scout",
    provider: "Meta",
    tier: "light",
    pricingPer1M: { input: 0.08, output: 0.3 },
    contextWindow: 327_680,
  },
  // ── Budget ($0.10 – $0.30/1M input) ──────────────────────────────────────
  {
    id: "google/gemini-2.5-flash-lite",
    label: "Gemini 2.5 Flash Lite",
    provider: "Google",
    tier: "light",
    pricingPer1M: { input: 0.1, output: 0.4 },
    contextWindow: 1_000_000,
  },
  {
    id: "openai/gpt-4.1-nano",
    label: "GPT-4.1 Nano",
    provider: "OpenAI",
    tier: "light",
    pricingPer1M: { input: 0.1, output: 0.4 },
    contextWindow: 1_047_576,
  },
  {
    id: "mistralai/pixtral-12b",
    label: "Pixtral 12B",
    provider: "Mistral",
    tier: "light",
    pricingPer1M: { input: 0.125, output: 0.125 },
    contextWindow: 4_096,
    notes: "Short context — best for single-page invoices",
  },
  {
    id: "meta-llama/llama-4-maverick",
    label: "Llama 4 Maverick",
    provider: "Meta",
    tier: "light",
    pricingPer1M: { input: 0.15, output: 0.6 },
    contextWindow: 1_048_576,
  },
  {
    id: "openai/gpt-4o-mini",
    label: "GPT-4o Mini",
    provider: "OpenAI",
    tier: "light",
    pricingPer1M: { input: 0.15, output: 0.6 },
    contextWindow: 128_000,
  },
  {
    id: "qwen/qwen2.5-vl-72b-instruct",
    label: "Qwen 2.5 VL 72B",
    provider: "Qwen",
    tier: "light",
    pricingPer1M: { input: 0.15, output: 0.6 },
    contextWindow: 32_768,
  },
  {
    id: "x-ai/grok-4.1-fast",
    label: "Grok 4.1 Fast",
    provider: "xAI",
    tier: "light",
    pricingPer1M: { input: 0.2, output: 0.5 },
    contextWindow: 2_000_000,
    notes: "Largest context window available",
  },
  {
    id: "google/gemini-2.5-flash",
    label: "Gemini 2.5 Flash",
    provider: "Google",
    tier: "standard",
    pricingPer1M: { input: 0.3, output: 2.5 },
    contextWindow: 1_000_000,
  },
  // ── Mid-range ($0.40 – $1.00/1M input) ───────────────────────────────────
  {
    id: "openai/gpt-4.1-mini",
    label: "GPT-4.1 Mini",
    provider: "OpenAI",
    tier: "standard",
    pricingPer1M: { input: 0.4, output: 1.6 },
    contextWindow: 1_047_576,
  },
  {
    id: "google/gemini-3-flash-preview",
    label: "Gemini 3 Flash",
    provider: "Google",
    tier: "standard",
    pricingPer1M: { input: 0.5, output: 3.0 },
    contextWindow: 1_000_000,
  },
  {
    id: "mistralai/mistral-large-2512",
    label: "Mistral Large 3",
    provider: "Mistral",
    tier: "standard",
    pricingPer1M: { input: 0.5, output: 1.5 },
    contextWindow: 262_144,
  },
  {
    id: "amazon/nova-pro-v1",
    label: "Nova Pro",
    provider: "Amazon",
    tier: "standard",
    pricingPer1M: { input: 0.8, output: 3.2 },
    contextWindow: 300_000,
  },
  // ── Premium ($1.00 – $3.00/1M input) ─────────────────────────────────────
  {
    id: "google/gemini-2.5-pro",
    label: "Gemini 2.5 Pro",
    provider: "Google",
    tier: "premium",
    pricingPer1M: { input: 1.25, output: 10.0 },
    contextWindow: 1_000_000,
  },
  {
    id: "openai/gpt-5.1",
    label: "GPT-5.1",
    provider: "OpenAI",
    tier: "premium",
    pricingPer1M: { input: 1.25, output: 10.0 },
    contextWindow: 400_000,
  },
  {
    id: "mistralai/pixtral-large-2411",
    label: "Pixtral Large",
    provider: "Mistral",
    tier: "premium",
    pricingPer1M: { input: 2.0, output: 6.0 },
    contextWindow: 131_072,
  },
  {
    id: "openai/gpt-4.1",
    label: "GPT-4.1",
    provider: "OpenAI",
    tier: "premium",
    pricingPer1M: { input: 2.0, output: 8.0 },
    contextWindow: 1_047_576,
  },
  {
    id: "google/gemini-3-pro-preview",
    label: "Gemini 3 Pro",
    provider: "Google",
    tier: "premium",
    pricingPer1M: { input: 2.0, output: 12.0 },
    contextWindow: 1_000_000,
  },
  {
    id: "openai/gpt-4o",
    label: "GPT-4o",
    provider: "OpenAI",
    tier: "premium",
    pricingPer1M: { input: 2.5, output: 10.0 },
    contextWindow: 128_000,
  },
  {
    id: "amazon/nova-premier-v1",
    label: "Nova Premier",
    provider: "Amazon",
    tier: "premium",
    pricingPer1M: { input: 2.5, output: 12.5 },
    contextWindow: 1_000_000,
  },
  {
    id: "anthropic/claude-sonnet-4",
    label: "Claude Sonnet 4",
    provider: "Anthropic",
    tier: "premium",
    pricingPer1M: { input: 3.0, output: 15.0 },
    contextWindow: 1_000_000,
  },
  {
    id: "anthropic/claude-sonnet-4.5",
    label: "Claude Sonnet 4.5",
    provider: "Anthropic",
    tier: "premium",
    pricingPer1M: { input: 3.0, output: 15.0 },
    contextWindow: 1_000_000,
  },
];

/** Lookup map: model id → BenchModel */
export const BENCH_MODELS_MAP = new Map(BENCH_MODELS.map((m) => [m.id, m]));

/** React Query key prefix */
export const BENCH_QUERY_KEYS = {
  pdfs: (establishmentId: string) => ["bench-pdfs", establishmentId] as const,
  runs: (benchPdfId: string) => ["bench-runs", benchPdfId] as const,
} as const;
